# Generated by Django 6.0.1 on 2026-02-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_shop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shop',
            table='Shop',
        ),
    ]
