# Generated by Django 6.0.1 on 2026-02-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=100)),
                ('ServicePrice', models.IntegerField()),
                ('ServiceStatus', models.BooleanField(default=True)),
                ('discount', models.IntegerField()),
            ],
            options={
                'db_table': ' Service',
            },
        ),
    ]
