# Generated by Django 6.0.1 on 2026-02-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewerName', models.CharField(max_length=100)),
                ('reviewRating', models.PositiveIntegerField()),
                ('reviewComment', models.TextField()),
                ('reviewStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
