# Generated by Django 6.0.1 on 2026-02-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_category_service_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='categoryId',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
