# Generated by Django 6.0.1 on 2026-02-06 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_category_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptopId', models.IntegerField()),
                ('brand', models.CharField()),
            ],
            options={
                'db_table': 'Laptop',
            },
        ),
        migrations.CreateModel(
            name='LaptopSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specId', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('laptopId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.laptop')),
            ],
            options={
                'db_table': 'LaptopSpecification',
            },
        ),
    ]
